repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    -   id: black
        language_version: python3.7
-   repo: git://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3.7
        args:
        - --add-import
        - from __future__ import absolute_import
        - --add-import
        - from __future__ import unicode_literals
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: detect-aws-credentials
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-json
    -   id: debug-statements
    -   id: end-of-file-fixer
-   repo: https://github.com/Yelp/detect-secrets
    rev: v0.13.1
    hooks:
    -   id: detect-secrets
        args:
        - --baseline
        - .secrets.baseline
        exclude: .*/tests/.*
exclude: (docs/|examples/|tests/|setup.py|Pipfile*)
