site_name: Document for gli
nav:
  - Home: index.md
  - 'Basic Concept': concept.md
  - 'User Guides':
      - 'Quick Start' : user-guide/quickstart.md
      - 'Config Files' : user-guide/confgfiles.md
      - 'Repository' : user-guide/repository.md
      - 'Group/User' : user-guide/users.md
      - 'Bulk Changes' : user-guide/bulk_update.md
      - 'Templates' : user-guide/templates.md
  - "References":
    - 'Developing': develop.md
    - 'Change log': changelog.md
  - About: about.md
theme:
  name: readthedocs
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - yaml
  shortcuts:
          help: 191    # ?
          next: 78     # n
          previous: 80 # p
          search: 83   # s
