site_name: glc
nav:
  - 'Index':
    - 'Home' : index.md
    - 'Changelog': changelog.md
    - 'Roadmap': roadmap.md
  - 'User Guides':
      'Basic Usage':
        - 'Setup' : guides/config.md
        - 'Group/User' : guides/users.md
        - 'Repository' : guides/repository.md
        - 'Merge Request' : guides/merge.md
        - 'Registry' : guides/registry.md
        - 'Snippet' : guides/snippet.md
      'Advanced Usage':
        - 'Bulk Update' : guides/bulk.md
        - 'Templates' : guides/templates.md
  - Others:
    - 'Contribute': develop.md
    - 'About': about.md
theme:
  name: readthedocs
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - yaml
  shortcuts:
          help: 191    # ?
          next: 78     # n
          previous: 80 # p
          search: 83   # s
