site_name: Document for gli
nav:
  - 'Basic':
    - 'Home' : index.md
    - 'Changelog': changelog.md
    - 'Roadmap': roadmap.md
  - 'User Guides':
      - 'Config Files' : user-guide/confgfiles.md
      - 'Repository' : user-guide/repository.md
      - 'Group/User' : user-guide/users.md
      - 'Bulk Changes' : user-guide/bulk.md
      - 'Templates' : user-guide/templates.md
  - "References":
    - 'Developing': develop.md
  - Other:
    - 'About': about.md
theme:
  name: readthedocs
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - yaml
  shortcuts:
          help: 191    # ?
          next: 78     # n
          previous: 80 # p
          search: 83   # s
