name: Basic Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make build
    - name: init pipenv
      run: pip install pipenv && pipenv install --dev
    - name: GitHub Action for pytest
      uses: cclauss/GitHub-Action-for-pytest@0.5.0

