name: Basic Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: make build

    - name: init pipenv
      run: pip install pipenv wheel&& pipenv install --dev

    - uses: cclauss/GitHub-Action-for-pytest@0.5.0

