name: Basic Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:

    - name: checkout scm
      uses: actions/checkout@v2
    - name: Build Docker image
      run: make build
    - name: setup pipenv
      uses: dschep/install-pipenv-action@v1
    - name: install virtualenv
      run: pipenv install --dev
    - name: run tests
      run: pipenv run make test

