name: unittest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: checkout scm
      uses: actions/checkout@v2
    - name: setup pipenv
      uses: dschep/install-pipenv-action@v1
    - name: install virtualenv
      run: pipenv install --dev
    - name: run tests
      run: pipenv run make test
    - name: coveralls
      run: pipenv run coveralls
    - name: check workspace
      run: ls -al
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
